### ISSUE TITLE
Custom state expose world coordinates

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#1]
When working with a custom state, being able to change the coordinate of the custom via world coordinates rather than local offsets may make it easier to position objects in Vroom.

**Comment by JvdBosch** [comment]
This is implemented in the version which will be released today.

**Comment by ThijsvbASML** [comment]
Seems to have broken the custom state node. Using the "point select" features gets the node to crash when selected.
![image](https://github.com/JvdBosch/vroomissues/assets/143791669/16890132-d6b6-47a1-ab51-f12f0e23c49d)

**Comment by JvdBosch** [comment]
I see, will be fixed today.

**Comment by ThijsvbASML** [comment]
Tested, works perfectly, Thanks Jaap.
