### ISSUE TITLE
Vroom group selection interupted on node hover

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#10]
When trying to select a group of objects using the "ctrl+right click" drag tool, if the mouse button is released over a node the selection will not be completed correctly and the option menu for the hovering node is opened instead.

![VroomNodeSelection](https://github.com/JvdBosch/vroomissues/assets/143791669/061c2261-2d6e-4deb-bc1b-9bd8041a1a5c)

**Comment by JvdBosch** [comment]
This is fixed in the version which will be released today.

**Comment by ThijsvbASML** [comment]
Works great.
