### ISSUE TITLE
Increment automatically added number to non-unique ID.

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#17]
When the ID of an object is not unique a "(1)" is added to make it unique. However when a "(1)" is already present. It would be more practical to increment the current "(1)" than adding multiple "(1)(1)(1)(1)". Especially when duplicating sets of objects this gets to large cascading IDs.
![image](https://github.com/JvdBosch/vroomissues/assets/143791669/e632802b-c9bc-47c8-b561-7330864c1faf)

**Comment by JvdBosch** [comment]
Fixed in upcoming version, later today.
