### ISSUE TITLE
Movement arrows are blocked by other geometry

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#3]
When moving objects around the world, movement arrows are commonly blocked by geometry in the scene. Could the rendering and collision detection of the arrows be done at a later stage to help ease of use?

![image](https://github.com/JvdBosch/vroomissues/assets/143791669/389a6808-2a9c-416b-ab9f-5b3e146c10ef)

**Comment by JvdBosch** [comment]
This is implemented in the version which will be released today.

**Comment by ThijsvbASML** [comment]
Works great.
