### ISSUE TITLE
Inventory indicator in VR.

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#31]
When going through interactive 2D animation, the suitcase icon will indicate if something is in your inventory. VR does not have an equivalent leaving it to supporting text/sound. A (visual) indicator that something is in your inventory could help make it clearer to the user that they can open the inventory.

Examples of implementation:
* Using an icon on the (opposite) wrist menu or hand.
* Making a hand/both hands glow (green)

**Comment by ThijsvbASML** [comment]
Artist impression by Diederik:
![MicrosoftTeams-image (3)](https://github.com/JvdBosch/vroomissues/assets/143791669/9b84e7b1-18c0-40e4-a89d-95f46525ec97)

**Comment by JvdBosch** [comment]
Added in upcoming version, please check.

**Comment by JvdBosch** [comment]
Fixed.
