### ISSUE TITLE
Animation Path / Tools 

### ISSUE THREAD

**Issue by DiederikJansen** [JvdBosch/vroomissues#36]
-Zoals eerder besproken zouden we graag een functie hebben waarbij de user een bepaalde path moet volgen met een tool of object zonder grote hoeveelheden custom states te moeten aanmaken. (Begin state -> Path met meerdere "checkpoints" -> endstate).

 (Voorbeeld: cleaning actie).
-Graag zouden wij ook de mogenlijkheid hebben om collisions met tools aan te zetten, zodoende dat we niet door een object 
  heen kunnen met het tool. (niet prioritair)

**Comment by JvdBosch** [comment]
A Bezier path has been included.
