### ISSUE TITLE
Vroom crashes while having a [standard with mistake] node with correct tools defined.

### ISSUE THREAD

**Issue by MichielLassche** [JvdBosch/vroomissues#39]
![image](https://github.com/JvdBosch/vroomissues/assets/109032712/d9f8dd3e-4d6c-4c3b-8c74-7429230c672e)

(I'm working with vroom portable)

**Comment by JvdBosch** [comment]
Should be fixed in next version. Please test

**Comment by MichielLassche** [comment]
Works
