### ISSUE TITLE
Tool and menu rendering always

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#4]
Allow the tool and main menu to render over other geometry in VR (Possibly if the ray were to hit the menu) as the menu is currently commonly blocked by geometry in a training.

**Comment by JvdBosch** [comment]
![image](https://github.com/JvdBosch/vroomissues/assets/39052144/ccaad6a7-b7b7-49da-83d2-7595981b28be)
Front draw option added in Configuration. Please try.

**Comment by ThijsvbASML** [comment]
Tested and works as requested, thanks again Jaap.
