### ISSUE TITLE
Hand outline highlight not applied to correct gesture

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#40]
When using the hand visualizer. Selecting the Highlight hand option and setting it to Outline does not use the correct gesture for the outline.

![image](https://github.com/JvdBosch/vroomissues/assets/143791669/d2f0afab-d223-4bae-98ae-73fce615e04d)

**Comment by JvdBosch** [comment]
Fixed in upcoming release
