### ISSUE TITLE
Materials not always rending transparency correctly

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#42]
When using transparent material on a model. The material may not always render as proper transparent and appear opaque instead. Selecting the object in the model tab and unselecting it may toggle the transparency. Running vroom may also toggle the transparency.

![image](https://github.com/JvdBosch/vroomissues/assets/143791669/77adcd06-061c-44da-b62b-111094ee0ca4)

![image](https://github.com/JvdBosch/vroomissues/assets/143791669/9d788d13-ec7d-466a-a305-8f3b7ad0ce41)

**Comment by JvdBosch** [comment]
Does this only occur in Authoring?

**Comment by ThijsvbASML** [comment]
No, both images are taken when running the training (From the authorer however). Not tested as stand alone training.

**Comment by JvdBosch** [comment]
Fixes in latest version
