### ISSUE TITLE
Middle mouse button in node plane deselects selected objects

### ISSUE THREAD

**Issue by ThijsvbASML** [JvdBosch/vroomissues#6]
When moving around a plane with nodes, Navigating the plane by using the middle mouse button deselects any nodes currently selected. Could this be changed so that it keeps the selection to make moving large numbers of nodes around the screen more practical.

![VroomNodeMovement](https://github.com/JvdBosch/vroomissues/assets/143791669/53a9ac4f-0329-44bc-ae6e-29a17d2c87d3)

**Comment by JvdBosch** [comment]
I will see if this can be done as you want, current workaround/functionality: holding the control key while moving keeps the selection active.

**Comment by JvdBosch** [comment]
It was a quick fix, implemented in next version.

**Comment by ThijsvbASML** [comment]
Works great.
